parameters:
        plentypark.doctrine_listener.class: ProjectSilly\BackendBundle\Listener\DoctrineListener

services:
    doctrine_global_listener:
        class: %plentypark.doctrine_listener.class%
        tags:
            - { name: doctrine.event_listener, event:preUpdate}
            - { name: doctrine.event_listener, event:postUpdate}
            - { name: doctrine.event_listener, event:postPersist}
            - { name: doctrine.event_listener, event:preRemove}
            - { name: doctrine.event_listener, event:postFlush}
        arguments:    [@service_container]

    area.entity.container_aware:
        class: ProjectSilly\CoreBundle\Entity\PublicPlace
        arguments: [@translator.default]